# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c08919320eedabd702370cee36edbe34ff6299a74b7ede68a31ccaf85b0128eaa95d72d8a566f91264f735b5d270a388d50699ea57e0f9cc48616d8af48624a

test:
  secret_key_base: 5a319f2ef3792137fd6da313b52c22644309d3292c01304c1b7a3e9a4ab3652e794b60c865fadac6d2de8512412a35ad2f4fc1c33d82ce76b6d875582d218b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
