# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b6972af838ece0db2325a2dadae5b32fb1b38a05240cf9b17ddfab16c3d7df50fd41e1f5fba3e1b18adbbaea94c4a67aac021b1f918672185794db1a6064898

test:
  secret_key_base: 1b7202b305094a401fa35d62e931baf16cf4871b209a2f7201cc694b3fe485b192dc7a1b8738684e14e38c4d5c935fee7a9d2d2a97ad631d4d887681eea8fb26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
